import {Box} from "@mui/material"
import Head from "next/head"
import { Navbar, SideBar } from "../ui"



interface Props {
    title?: string,
    children?: JSX.Element
}

export const Layout:React.FunctionComponent<Props> = ({title = "OpenJira",children}) => {
  return (
    <Box sx ={{flexFlow: 1}}>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
        <SideBar/>
        <Box sx ={{padding:"10px 20px"}}>
            {children}
        </Box>
    </Box>
  )
}
